# Generated by Django 4.2.1 on 2023-05-11 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_rename_banners_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='images',
            new_name='image',
        ),
    ]
