# Generated by Django 4.1.7 on 2023-03-30 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Customer name', max_length=200)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('birthday', models.DateField(default='2000-01-01')),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/user/%Y/%m/%D/')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.account')),
            ],
        ),
    ]
