# Generated by Django 4.1.7 on 2023-04-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Customer name', max_length=200)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('birthday', models.DateField(default='2000-01-01')),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/user/%Y/%m/%D/')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
