# Generated by Django 4.1.7 on 2023-04-06 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Delivering'), (3, 'Delivered'), (4, 'Cancelled')])),
                ('name', models.CharField(default='Customer Name', max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('payment', models.IntegerField(choices=[(1, 'COD'), (2, 'Banking'), (3, 'Others')])),
                ('is_paid', models.BooleanField(default=False)),
                ('note', models.TextField()),
                ('total', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_sale', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('sale_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productdetail')),
            ],
        ),
    ]
