# Generated by Django 4.1.7 on 2023-03-30 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Customer Name', max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.DateTimeField()),
                ('isPaid', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Delivering'), (3, 'Delivered'), (4, 'Cancelled')])),
                ('payment', models.IntegerField(choices=[(1, 'COD'), (2, 'Banking'), (3, 'Others')])),
                ('note', models.TextField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_sale', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('sale_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
