# Generated by Django 4.1.7 on 2023-04-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_product_orderitem_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(1, 'COD'), (2, 'Chuyển khoản ngân hàng'), (3, 'Khác')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Chờ xác nhận'), (2, 'Đang chuẩn bị hàng'), (3, 'Đang giao hàng'), (4, 'Đã giao'), (5, 'Đã hủy')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateField(),
        ),
    ]
