# Generated by Django 4.1.7 on 2023-04-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Chờ xác nhận'), (2, 'Chờ lấy hàng'), (3, 'Đang giao hàng'), (4, 'Đã giao'), (5, 'Đã hủy')]),
        ),
    ]
